### PR TITLE
Add `datetime` column for easy reading

### PR DESCRIPTION
**Pull request by ChrisToxz**
Added default `datetime` column for human-readable date and time.
Usefull for easy parsing or when exporting to logviewer/excel

### CODE REVIEW

**Comment by cherryred5959** [comment]
It seems that storing the same data in two columns is not a good idea.

Do you have any other ideas for changing the existing column in a different way?

**Comment by ChrisToxz** [comment]
The issue is that the default column is an integer and not datetime.
I can look into it to make it at a option to decide one of them.

Any ideas?

**Comment by cherryred5959** [comment]
@ChrisToxz I think the database is just storage.

For example, if you need to show the database in a PHP application, an appropriate transition is possible, and even when using the SQL GUI, you can execute a formatable query.

And, I don't have an idea either for table changes. 😢

**Comment by amacado** [comment]
Hello @ChrisToxz, your contribution is welcome! I've taken over maintenance for this project and I think using the `datetime` type is more common than the current implementation using a unix timestamp. I'm currently preparing a v2 breaking change update for this project and replacing the current time column with a timestamp will be part of it. Feel free to create a pull request with base https://github.com/waza-ari/monolog-mysql/tree/v2.x. Since this pull request is over 3 years I'll close it to re-create it. I'll give you some days to consider implementing the update by yourself, otherwise I'll do it on my own. best regards!

**Pull request closed without merging**
