### PR TITLE
Allows user to specify date-time field for time instead of seconds since Epoch.

### PR DESCRIPTION
**Pull request by teehays**
I really prefer to see visible dates using datetime and wanted to have this for my logging. I've also made an attempt to improve the readability of the table creation PDO request as it now has more variables in it. 

With the $table variable now holding the table_name and optional time_format field, it would allow for further specifying of table setup if needed.

### CODE REVIEW

**Comment by waza-ari** [comment]
Hi teehays, thanks for your pull request. I will look into it tomorrow and then merge/release new version. Thanks for contributing!

**Comment by teehays** [comment]
Hi Daniel,

Thanks so much for your message, I hope you can see the value of my
additions. This was my first Pull Request so I'm obviously happy to make
some changes.

I really love being able to log to MySql, in certain circumstances it's
just really, really handy and it's great that this module is available for
Laravel.

Thanks once again.

Tytn

**Comment by waza-ari** [comment]
Hi teehays, thank you again and sorry very much that I did not answer earlier. I don't know about Lavarel. The problem with your PR is that it would break backwards compatibility as the class signature would change. Is it possible to make this class compatible with Lavarel without breaking compatibility?

**Comment by THaysSureFlap** [comment]
The method signature isn't compromised, but it will cause problems with backwards compatibility so I will work on it.

**Comment by waza-ari** [comment]
Sorry, I haven't seen the additional changes you introduced. Going to look at this soon.

**Comment by waza-ari** [comment]
I've merged PR #20, which actually is a little more general, allowing even more time formats. Please check the development branch to see wether this suites your needs. Otherwise, please re-open this PR and explain why we still need the features of this PR.

**Pull request closed without merging**
